# Generated by Django 3.2.6 on 2021-08-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='data',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='choice',
            name='content',
            field=models.CharField(default='', max_length=100),
        ),
    ]
